=== tomaszpietr/RoweremPoTrojmiescie/moje_hobby.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">

	<xs:element name="moje_hobby">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nav" type="navType"/>
				<xs:element name="informacje" type="informationType"/>
				<xs:element name="trasy" type="routesType"/>
				<xs:element name="aplikacje" type="appsType" />
				<xs:element name="kontakt" type="contactType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:attribute name="source">
		<xs:simpleType>
			<xs:restriction base="xs:anyURI"/>
		</xs:simpleType>
	</xs:attribute>
	
	<xs:attribute name="content">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:attribute>
	
	<xs:attribute name="kind">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="enter"/>
				<xs:enumeration value="tick"/>
				<xs:enumeration value="choose"/>
				<xs:enumeration value="attach"/>
				<xs:enumeration value="list"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

	<xs:complexType name="navType">
		<xs:sequence>
			<xs:element name="strona" type="pageType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="pageType">
		<xs:sequence>
			<xs:element name="tytuł" type="titleType" />
			<xs:element name="aplikacje" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute ref="content" use="required"/>
		<xs:attribute ref="source" use="required"/>
	</xs:complexType>

	<xs:simpleType name="titleType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	
	<xs:complexType name="informationType">
		<xs:sequence>
			<xs:element name="tekst" type="longStringType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="zdjęcia" type="imagesType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="imagesType">
		<xs:sequence>
			<xs:element name="zdjęcie" type="imageType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="imageType">
		<xs:attribute ref="source" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="routesType">
		<xs:sequence>
			<xs:element name="trasa" type="routeType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="routeType">
		<xs:sequence>
			<xs:element name="nazwa" type="xs:string"/>
			<xs:element name="mapa" type="imageType" />
			<xs:element name="dystans" type="distanceType" />
			<xs:element name="opis" type="longStringType" />
			<xs:element name="szczegóły" type="linkType" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="distanceType">
		<xs:simpleContent>
			<xs:extension base="shortStringType">
				<xs:attribute name="unit" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="km|m"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="linkType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="source" type="xs:anyURI" use="required"/>
				<xs:attribute name="system" use="optional">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="android|ios"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="type" use="optional">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="downloadapp|gotopage"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:simpleType name="longStringType">
		<xs:restriction base="xs:string">
			<xs:minLength value="50"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="shortStringType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="20"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="appsType">
		<xs:sequence>
			<xs:element name="wstęp" type="longStringType"/>
			<xs:element name="aplikacja" type="appType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="appType">
		<xs:sequence>
			<xs:element name="nazwa" type="shortStringType"/>
			<xs:element name="ikona" type="imageType"/>
			<xs:element name="opis" type="longStringType"/>
			<xs:element name="linki" type="linksType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="linksType">
		<xs:sequence>
			<xs:element name="link" type="linkType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="contactType">
		<xs:sequence>
			<xs:element name="wstęp" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="imię" type="formType"/>
			<xs:element name="e-mail" type="formType"/>
			<xs:element name="tematy" type="listType"/>
			<xs:element name="temat_inny" type="formType"/>
			<xs:element name="plik" type="formType"/>
			<xs:element name="imię_na_stronie">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="tekst" type="xs:string"/>
					<xs:element name="wybór" type="xs:string"/>
					<xs:element name="wybór" type="xs:string"/>
				</xs:sequence>
			<xs:attribute ref="kind" />
			</xs:complexType>
			</xs:element>
		<xs:element name="aplikacje">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="tekst" type="xs:string"/>
					<xs:element name="aplikacja" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			<xs:attribute ref="kind" />
			</xs:complexType>
		</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="listType">
		<xs:sequence>
			<xs:element name="tekst" type="xs:string"/>
			<xs:element name="temat" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	<xs:attribute ref="kind" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="formType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute ref="kind"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== tomaszpietr/RoweremPoTrojmiescie/moje_hobby.xml
<?xml version="1.0" encoding="utf-8"?>
<moje_hobby xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="moje_hobby.xsd">
	<nav>
		<strona content="information" source="index.html">
			<tytuł>Strona główna</tytuł>
		</strona>
		<strona content="routes" source="trasy.html">
			<tytuł>Trasy rowerowe</tytuł>
		</strona>
		<strona content="apps" source="aplikacje.html">
			<tytuł>Aplikacje na smartfona</tytuł>
			<aplikacje content="apps">
				<aplikacja name="naviki" source="aplikacje.html#naviki">Naviki</aplikacja>
				<aplikacja name="googlemaps" source="aplikacje.html#googlemaps">Google Maps</aplikacja>
				<aplikacja name="activy" source="aplikacje.html#activy">Activy</aplikacja>
				<aplikacja name="strava" source="aplikacje.html#strava">Strava</aplikacja>
			</aplikacje>
		</strona>
		<strona content="contact" source="kontakt.html">
			<tytuł>Kontakt</tytuł>
		</strona>
	</nav>
	<informacje>
		<tekst>
			Strona internetowa poświęcona jest mojemu hobby, jakim są wycieczki rowerowe po Trójmieście. Zawiera ciekawe trasy oraz aplikacje, służące do pozyskiwania szczegółowych informacji na temat przejazdów.
			Dlaczego lubię jeździć na rowerze?
			Szybko i sprawnie mogę dostać się do wybranego miejsca w mieście i nie muszę martwić się o brak miejsca parkingowego
			Pomaga mi to zadbać o moje zdrowie, samopoczucie i kondycję
			Podczas wycieczek poznaję ciekawe miejsca w mieście oraz mogę dostrzec piękno natury
			Rower jest bezpłatnym środkiem transportu
		</tekst>
		<zdjęcia>
			<zdjęcie source="rowerplaza.png"></zdjęcie>
			<zdjęcie source="rowerplaza.png"/>
		</zdjęcia>
	</informacje>
	<trasy>
		<trasa>
			<nazwa>Chełm - lasy oliwskie - ścieżka nadmorska</nazwa>
			<mapa source="img/mapa1.png"/>
			<dystans unit="km">42,3</dystans>
			<opis>Wyruszamy z Chełmu i sprawnie docieramy przez Morenę do Matemblewa, gdzie zaczyna się leśny odcinek. Po przejeździe pod Słowackiego ruszamy asfaltem w stronę Oliwy. W tej lokalizacji opcji tras jest wiele, ten wariant wycieczki omija zjazd asfaltem przez las, jedziemy zaś drogą gruntową prowadzącą wprost do "drogi węglowej", którą wspinamy się na Owczarnię. Tam, jadąc chwilę "drogą marnych mostów" skręcamy w las, by osiągnąć szczyt doliny Radości, którą zjeżdżamy do Oliwy. Dojeżdżamy do Spacerowej i jedziemy do góry wzdłuż drogi, by finalnie znaleźć się na początku "drogi nadleśniczych" którą kierujemy się w stronę Borodzieja. Skręcamy w bardzo przyjemny zjazd do doliny świemierowskiej, a tam już czeka nas odcinek miejski. Przejeżdżamy nad torami i do domu powracamy już wzdłuż morza.</opis>
			<szczegóły source="https://www.traseo.pl/trasa/chelm-lasy-oliwskie-powrot-sciezka-nadmorska">Kliknij tutaj</szczegóły>
		</trasa>
		<trasa>
			<nazwa>Przymorze - Bursztynowa Góra</nazwa>
			<mapa source="img/mapa2.png"/>
			<dystans unit="km">52</dystans>
			<opis>Na Jasień dostajemy się jednym z najłagodniejszych podjazdów - najpierw ulicą Potokową, a następnie drogą z płyt betonowych, która jest jej przedłużeniem. Prowadzi ona przez las wzdłuż potoku Jasień. Po kilkuset metrach skręcamy w lewo, by jadąc po asfalcie minąć stację PKM Gdańsk Jasień. Przejeżdżając w sumie cztery ronda docieramy do Kartuskiej, a następnie skręcamy w prawo w Źródlaną. Po prawej stronie widzimy Jezioro Jasień, skręcamy w lewo i jadąc chwilę wzdłuż wjeżdżamy na wiadukt nad trasą S6. Tuż za restauracją Wróblówka wjeżdżamy do lasu. Tu ma swój początek trasa rowerowa "Wolność jest w naturze". Nie jest ona zbyt trudna, na rowerze trekkingowym też da się przejechać. Oznakowanie jest dość dobre, chociaż w niektórych miejscach znaków brakuje, np gdy zaraz po skręcie w lewo trzeba skręcić w prawo jest tylko znak mówiący o pierwszej zmianie kierunku. Najkorzystniej jest jechać wzdłuż zachodniego brzegu Jeziora Otomińskiego, a następnie w miejscu opisanym jako "rozwidlenie trasy" skręcić w prawo, by dojechać do rezerwatu "Bursztynowa Góra". Niestety pojechaliśmy tam w lewo i dalszą część trasy pokonaliśmy nieco inaczej niż chcieliśmy, Oprócz tajemniczej Bursztynowej Góry, która była miejscem wydobycia bursztynu można zobaczyć Czarny Staw, oraz tereny bagienne. By nie jechać tą samą trasą objechaliśmy jezioro od wschodu. Po krótkim odpoczynku na najpopularniejszej tu plaży skierowaliśmy się dość dziurawą leśną drogą na północ. Jadąc ulicą Otomińską przecięliśmy Kartuską, kontynuując jazdę Kalinową i przejeżdżając przy ogródkach działkowych docieramy do torów kolejowych oraz zbiornika retencyjnego Kiełpinek. Jest to miejsce warte zobaczenia. Po jego objechaniu skierowaliśmy się najpierw piaskową, a następnie asfaltową Sąsiedzką do Kościoła pw. św. Walentego. Jadąc dalej Jesienną dojechaliśmy do Budowlanych. Teraz już tylko skręt w lewo w Słowackiego i dalej po super DDR do Radarowej. Kontynuując jazdę tą ulicą dojechaliśmy do Owczarni. Dalej już tylko z górki, po drodze mijaliśmy Rezerwat Źródliska w Dolinie Ewy. Kościerską dotarliśmy do Spacerowej a następnie Opata Jacka Rybińskiego.</opis>
			<szczegóły source="https://www.traseo.pl/trasa/przymorze-bursztynowa-gora">Kliknij tutaj</szczegóły>
		</trasa>
		<trasa>
			<nazwa>Wycieczka przyrodniczo-industrialna</nazwa>
			<mapa source="img/mapa3.png"/>
			<dystans unit="km">39,8</dystans>
			<opis>Z Dąbrowy Rdestową, Krzemową, Kacze Buki, Myśliborską i Gnieźnieńską do Osowy. Chełmińską, Sambora, Nowym Światem, Planetarną do Barniewic. Lipową, Barniewicką i Piaskową do Rębiechowa. Gdańską, Słowackiego, Słowackiego, Azymutalną, Spadochroniarzy, Słowackiego do Matarni. Kleszą Drogą (zwaną Drogą Siedmiu Garbów), Szwedzką Groblą, Bytowską, Kościerską do Oliwy. Spacerową, Drogą Rynarzewską i Drogą Długa Linia do Gołębiewa. Niebieskim Szlakiem, Orną i Starodworcową do Wielkiego Kacka i Karwin. Chwaszczyńską, Nowowiczlińską i Rdestową na Dąbrowę.</opis>
			<szczegóły source="https://www.traseo.pl/trasa/wycieczka-przyrodniczo-industrialna">Kliknij tutaj</szczegóły>
		</trasa>
		<trasa>
			<nazwa>Trasa nadmorska</nazwa>
			<mapa source="img/mapa4.png"/>
			<dystans unit="km">32,8</dystans>
			<opis>Łatwa, rekreacyjna trasa z licznymi atrakcjami, którą z chęcią pokona każdy miłośnik roweru. Przez większość odcinków wiedzie wydzielonymi drogami rowerowymi, o doskonałej nawierzchni, wzdłuż morza. Jest to jeden z najbardziej atrakcyjnych i rozpoznawalnych produktów turystyki rowerowej w Trójmieście, z którego w sezonie letnim korzysta wielu mieszkańców i turystów. Trasa jest dobrze skomunikowana z transportem miejskim, przez co bez problemu można dotrzeć na wybrany punkt ścieżki. Dodatkowym jej atutem są liczne punkty gastronomiczne oraz miejsca odpoczynku przez co pokonanie tej 30 kilometrowej drogi jest przyjemne i mało uciążliwe. Proponowana trasa rozpoczyna się przy dworcu kolejowym Gdynia Główna i wiedzie przez Gdynię Orłowo, Sopot oraz nadmorskie dzielnice Gdańska: Jelitkowo, Przymorze, Zaspa, Brzeźno oraz Letnicę. Koniec wycieczki przewidziany jest w okolicach stacji SKM Politechnika Gdańska.</opis>
			<szczegóły source="https://www.traseo.pl/trasa/trasa-nadmorska-w-trojmiescie">Kliknij tutaj</szczegóły>
		</trasa>
		<trasa>
			<nazwa>Jesienne Trójmiasto</nazwa>
			<mapa source="img/mapa5.png"/>
			<dystans unit="km">36,9</dystans>
			<opis>Trasa zaczyna się w Gdyni i biegnie na terenie malowniczego Trójmiejskiego Parku Krajobrazowego i ścieżkami rowerowymi. Po ok. czterech kilometrach dojeżdżamy do zamkniętego dla ruchu wyasfaltowanego odcinka przy leśniczówce Gołebiewko. (Doskonałe miejsce na treningi także dla kolaży szosowych). Jedziemy asfaltem sześć kilometrów i odbijamy w lewo, by wjechać na punkt widokowy. Z punktu rozpościera się piękny widok na Sopot i Zatokę Gdańską.(Z punktu jest możliwość skrócenia wycieczki i powrotu do Gdyni). Ponieważ czas goni, zjeżdżamy do Sopotu i ścieżkami rowerowymi, których w Gdańsku nie brakuje, jedziemy do Politechniki Gdańskiej, gdzie jesteśmy już umówieni z resztą ekipy. Z politechniki jedziemy nad morze. Jesień to według mnie najlepszy okres na nadmorską ścieżkę. W czasie wakacji staram się ją omijać. Pomimo że ścieżka ma dwa pasy, jest na niej tyle ludzi, że jazda to ciągły slalom. Natomiast jesienią to wymarzone miejsce z dala od samochodów z rześkim powietrzem znad Bałtyku. Dodatkowo przy ścieżce ustawione są latarnie, co umożliwia poruszanie się po zmroku. Ścieżką z mola w Gdańsku (niedaleko są knajpki, można zatrzymać się na herbatkę) jedziemy w stronę Sopotu. Nie ma dużo rowerzystów, pewnie dlatego, że jesień. Szybko robi się ciemno. Dojeżdżamy do mola w Sopocie. Latem ciężko tam przejść, teraz spotykamy tylko kilka osób. Z Sopotu jest plan, by pojechać klifami, jednak w lesie jest już na tle ciemno, że lampki nie wystarczają. Postanawiamy zatem pojechać do domów na kolacyjkę. :)</opis>
			<szczegóły source="https://www.traseo.pl/trasa/jesienne-trojmiasto">Kliknij tutaj</szczegóły>
		</trasa>
	</trasy>
	<aplikacje>
		<wstęp>Aplikacje na rower znacznie usprawniają poruszanie się jednośladem i planowanie wycieczek. Pozwalają m.in. sprawdzić mapy rowerowe czy ustawić nawigację rowerową. Większość tradycyjnych aplikacji z GPS-em przeznaczonych jest przede wszystkim dla kierowców samochodów – mogą one nie wskazywać dróg, które dostępne są tylko dla rowerzystów i pieszych.Poniżej zostało przedstawionych kilka propozycji aplikacji, które warto zainstalować.
		</wstęp>
		<aplikacja>
			<nazwa>Naviki</nazwa>
			<ikona source="img/naviki.png"/>
			<opis>Obsługiwana zarówno na iOS oraz Androidzie. Jest to aplikacja nastawiona na tworzenie i optymalizacje tras rowerowych, działająca zarówno z połączeniem internetowym jak i bez niego. Programiści zadbali o dużą ilość paczek językowych, w których znalazła się i Polska. Jedynym minusem jest brak funkcji sportowych, takich jak obliczanie średniej prędkości na trasie czy obliczanie przejechanego dystansu i czasu na pokonanie go.</opis>
			<linki>
